const ListProdSimilares = [
    {
        id:1,
        img:require('../images/FenderHendrix.jpg'),
        desc:"Guitarra eléctrica Fender Artist Jimi Hendrix Stratocaster de aliso...",
        precio: 662.057,
        categoria:"Guitarra Eléctrica",
        modelo:"Stratocaster",
        orientacion:"Diestro",
        color:"Olympic white",
        cuerpo:"Aliso",
        diapason:"Arce",
        acabado:"Uretano brillante",
        moddet:"-",
        origen:"Mexico",
        cantidad:1
    },
    {
        id:2,
        img:require('../images/LesPaulModern.jpg'),
        desc:"Guitarra eléctrica Gibson Modern Collection Les Paul Studio de arce/caoba...",
        precio: 574.999,
        categoria:"Guitarra Eléctrica",
        modelo:"Les Paul",
        orientacion:"Diestro",
        color:"Smokehouse burst",
        cuerpo:"Arce/Caoba",
        diapason:"Palo de rosa",
        acabado:"Brillante",
        moddet:"LPST00KHCH1",
        origen:"-",
        cantidad:2
    },
    {
        id:3,
        img:require('../images/LesPaulSTBlue.jpg'),
        desc:"Guitarra eléctrica Gibson Les Paul Standard de arce/caoba 2018 cobalt...",
        precio: 1.532475,
        categoria:"Guitarra Eléctrica",
        modelo:"Les Paul",
        orientacion:"Diestro",
        color:"Cobalt burst",
        cuerpo:"Arce/Caoba",
        diapason:"Palo de rosa",
        acabado:"Brillante",
        moddet:"-",
        origen:"Mexico",
        cantidad:0
    },
    {
        id:4,
        img:require('../images/tvSamsungSeries5.jpg'),
        desc:"Smart TV Samsung Series 5 UN43T5300AGCZB LED Full HD 43",
        precio: 83.999,
        modelo: "UN43T5300AGCZB",
        categoria:"TV",
        voltaje:"220V - 240V",
        frecuencia:"50 Hz x 60 Hz",
        tipodepantalla:"LED",
        tamañodepantalla:"43",
        tipoderesolucion:"Full HD",
        conHDR:"Sí"
    },
    {
        id:5,
        img:require('../images/tvPhilips7000.jpg'),
        desc:"Smart TV Philips 7000 Series 50PUD7406/77 LED 4K 50",
        precio: 102.999,
        modelo: "50PUD7406/77",
        categoria:"TV",
        voltaje:"110V/240V",
        frecuencia:"50 Hz x 60 Hz",
        tipodepantalla:"LED",
        tamañodepantalla:"50",
        tipoderesolucion:"4K",
        conHDR:"Sí"
    },
    {
        id:6,
        img:require('../images/tvSamsungSeries5.jpg'),
        desc:"Smart TV Samsung Series 5 UN43T5300AGCZB LED Full HD 43",
        precio: 83.999,
        modelo: "UN43T5300AGCZB",
        categoria:"TV",
        voltaje:"220V - 240V",
        frecuencia:"50 Hz x 60 Hz",
        tipodepantalla:"LED",
        tamañodepantalla:"43",
        tipoderesolucion:"Full HD",
        conHDR:"Sí"
    }
]

export default ListProdSimilares;