const ListProdVisitados = [
    {
        id:1,
        img:require('../images/TelecasterFender.jpg'),
        desc:"Guitarra eléctrica Fender American Vintage '52 Telecaster de fresno...",
        precio: 2.404465,
        categoria:"Guitarra Eléctrica",
        modelo:"Telecaster",
        orientacion:"Diestro",
        color:"Butterscotch blonde",
        cuerpo:"Fresno",
        diapason:"Arce",
        acabado:"Laca nitrocelulosa",
        moddet:"0110202850",
        origen:"USA",
        cantidad:0
    },
    {
        id:2,
        img:require('../images/FenderStrPlayer.jpg'),
        desc:"Guitarra eléctrica Fender Player Stratocaster de aliso black brillante con...",
        precio: 574.999,
        categoria:"Guitarra Eléctrica",
        modelo:"Stratocaster",
        orientacion:"Diestro",
        color:"Black",
        cuerpo:"Aliso",
        diapason:"Arce",
        acabado:"Brillante",
        moddet:"0144502506",
        origen:"-",
        cantidad:1
    },
    {
        id:3,
        img:require('../images/TelecasterOnas.jpg'),
        desc:"Guitarra eléctrica Onas TL telecaster de lenga blue wood laca con diapasón...",
        precio: 57.419,
        categoria:"Guitarra Eléctrica",
        modelo:"Telecaster",
        orientacion:"Diestro",
        color:"Blue wood",
        cuerpo:"Lenga",
        diapason:"Palo de rosa",
        acabado:"Laca",
        moddet:"-",
        origen:"-",
        cantidad:38
    },
    {
        id:4,
        img:require('../images/tvSamsungSeries6.jpg'),
        desc:"Smart TV Samsung Series 6 QN55Q60AAGCZB QLED 4K 55",
        precio: 179.999,
        modelo: "QN55Q60AAGCZB",
        categoria:"TV",
        voltaje:"220V - 240V",
        frecuencia:"50 Hz x 60 Hz",
        tipodepantalla:"QLED",
        tamañodepantalla:"55",
        tipoderesolucion:"4 K",
        conHDR:"Sí"
    },
    {
        id:5,
        img:require('../images/tvRCA.jpg'),
        desc:"Smart TV RCA AND55FXUHD LCD 4K 55 220V - 240V",
        precio: 123.999,
        modelo: "-",
        categoria:"TV",
        voltaje:"110V/240V",
        frecuencia:"50 Hz x 60 Hz",
        tipodepantalla:"LCD",
        tamañodepantalla:"55",
        tipoderesolucion:"4K",
        conHDR:"Sí"
    },
    {
        id:6,
        img:require('../images/tvTCLP7252.jpg'),
        desc:"Smart TV TCL P725-Series 55P725 DLED 4K 55 100V/240V",
        precio: 139.699,
        modelo: "-",
        categoria:"TV",
        voltaje:"220V - 240V",
        frecuencia:"50 Hz x 60 Hz",
        tipodepantalla:"LCD",
        tamañodepantalla:"55",
        tipoderesolucion:"4 K",
        conHDR:"Sí"
    },
    {
        id:7,
        img:require('../images/FenderChampionSeries100.jpg'),
        desc:"Amplificador Fender Champion Series 100 Valvular para guitarra de 100W color negro/plata 220V",
        precio: 183.315,
        categoria:"Amplificador",
        tipo:"Combo",
        tecnologia:"Valvular",
        alimentacion:"Corriente Eléctrica",
        instRecomendado:"Guitarra",
        cantidaddecanales:2,
        potenciadesalida:"100W",
        peso:"18Kg",
        color:"Negro/Plata"
    },
    {
        id:8,
        img:require('../images/BugueraInfiniumV22.jpg'),
        desc:"Amplificador Bugera Infinium V22 Valvular para guitarra de 22WV",
        precio: 241.787,
        categoria:"Amplificador",
        tipo:"Combo",
        tecnologia:"Valvular",
        alimentacion:"Corriente Eléctrica",
        instRecomendado:"Guitarra",
        cantidaddecanales:2,
        potenciadesalida:"22W",
        peso:"20Kg",
        color:"Negro"
    },
    {
        id:9,
        img:require('../images/VoxCustomSeriesAC15C1.jpg'),
        desc:"Amplificador VOX Custom Series AC15C1 Valvular para guitarra de 15W color negro",
        precio: 552.713,
        categoria:"Amplificador",
        tipo:"Combo",
        tecnologia:"Valvular",
        alimentacion:"Corriente Eléctrica",
        instRecomendado:"Guitarra",
        cantidaddecanales:2,
        potenciadesalida:"15W",
        peso:"25Kg",
        color:"Negro/Marron"
    },
    {
        id:10,
        img:require('../images/PlayStation5DigitalEdition.jpg'),
        desc:"Sony PlayStation 5 825GB Digital Edition  color blanco y negro",
        precio: 354.499,
        categoria:"Games",
        edicion:"Standard",
        color:"Blanco/Negro",
        capacidad:"825GB",
        tiposdememoria: "GDDR6",
        memoriaRam: "16GB",
        conWiFi: "Sí",
        conHDMI: "Sí",
        subModelo: "-" 
    },
    {
        id:11,
        img:require('../images/PlayStation3.jpg'),
        desc:"Sony PlayStation 3 Super Slim 500GB Standard  color charcoal black",
        precio: 107.490,
        categoria:"Games",
        edicion:"Standard",
        color:"Charcoal black",
        capacidad:"500GB",
        tiposdememoria: "XDR, GDDR3",
        memoriaRam: "256MB",
        conWiFi: "-",
        conHDMI: "-",
        subModelo: "Super Slim" 
    },
    {
        id:12,
        img:require('../images/PlayStation825GB.jpg'),
        desc:"Sony PlayStation 5 825GB Horizon Forbidden West Bundle  color blanco y negro",
        precio: 539.999,
        categoria:"Games",
        edicion:"Horizon Forbidden West Bundle",
        color:"Blanco/Negro",
        capacidad:"825GB",
        tiposdememoria: "GDDR6",
        memoriaRam: "16GB",
        conWiFi: "Sí",
        conHDMI: "Sí",
        subModelo: "-" 
    },
    {
        id:13,
        img:require('../images/CortadoraPastoEinhell.jpg'),
        desc:"Maquina Cortar Pasto Einhell",
        precio: 662.057,
        categoria:"Podadora",
        modelo:"Stratocaster",
        orientacion:"Diestro",
        color:"Olympic white",
        cuerpo:"Aliso",
        diapason:"Arce",
        acabado:"Uretano brillante",
        moddet:"-",
        origen:"Mexico",
        cantidad:1
    },
    {
        id:14,
        img:require('../images/CortadoraPastoOmaha.jpg'),
        desc:"Maquina Cortar Pasto Omaha",
        precio: 574.999,
        categoria:"Podadora",
        modelo:"Les Paul",
        orientacion:"Diestro",
        color:"Smokehouse burst",
        cuerpo:"Arce/Caoba",
        diapason:"Palo de rosa",
        acabado:"Brillante",
        moddet:"LPST00KHCH1",
        origen:"-",
        cantidad:2
    },
    {
        id:15,
        img:require('../images/CortadoraPastoGamma.jpg'),
        desc:"Maquina Cortar Pasto Gamma",
        precio: 1.532475,
        categoria:"Podadora",
        modelo:"Les Paul",
        orientacion:"Diestro",
        color:"Cobalt burst",
        cuerpo:"Arce/Caoba",
        diapason:"Palo de rosa",
        acabado:"Brillante",
        moddet:"-",
        origen:"Mexico",
        cantidad:0
    }
]

export default ListProdVisitados;