const ListProdSimilares = [
    {
        id:1,
        img:require('../images/FenderHendrix.jpg'),
        desc:"Guitarra eléctrica Fender Artist Jimi Hendrix Stratocaster de aliso...",
        precio: 662.057,
        categoria:"Guitarra Eléctrica",
        modelo:"Stratocaster",
        orientacion:"Diestro",
        color:"Olympic white",
        cuerpo:"Aliso",
        diapason:"Arce",
        acabado:"Uretano brillante",
        moddet:"-",
        origen:"Mexico",
        cantidad:1
    },
    {
        id:2,
        img:require('../images/LesPaulModern.jpg'),
        desc:"Guitarra eléctrica Gibson Modern Collection Les Paul Studio de arce/caoba...",
        precio: 574.999,
        categoria:"Guitarra Eléctrica",
        modelo:"Les Paul",
        orientacion:"Diestro",
        color:"Smokehouse burst",
        cuerpo:"Arce/Caoba",
        diapason:"Palo de rosa",
        acabado:"Brillante",
        moddet:"LPST00KHCH1",
        origen:"-",
        cantidad:2
    },
    {
        id:3,
        img:require('../images/LesPaulSTBlue.jpg'),
        desc:"Guitarra eléctrica Gibson Les Paul Standard de arce/caoba 2018 cobalt...",
        precio: 1.532475,
        categoria:"Guitarra Eléctrica",
        modelo:"Les Paul",
        orientacion:"Diestro",
        color:"Cobalt burst",
        cuerpo:"Arce/Caoba",
        diapason:"Palo de rosa",
        acabado:"Brillante",
        moddet:"-",
        origen:"Mexico",
        cantidad:0
    },
    {
        id:4,
        img:require('../images/tvSamsungSeries5.jpg'),
        desc:"Smart TV Samsung Series 5 UN43T5300AGCZB LED Full HD 43",
        precio: 83.999,
        modelo: "UN43T5300AGCZB",
        categoria:"TV",
        voltaje:"220V - 240V",
        frecuencia:"50 Hz x 60 Hz",
        tipodepantalla:"LED",
        tamañodepantalla:"43",
        tipoderesolucion:"Full HD",
        conHDR:"Sí"
    },
    {
        id:5,
        img:require('../images/tvPhilips7000.jpg'),
        desc:"Smart TV Philips 7000 Series 50PUD7406/77 LED 4K 50",
        precio: 102.999,
        modelo: "50PUD7406/77",
        categoria:"TV",
        voltaje:"110V/240V",
        frecuencia:"50 Hz x 60 Hz",
        tipodepantalla:"LED",
        tamañodepantalla:"50",
        tipoderesolucion:"4K",
        conHDR:"Sí"
    },
    {
        id:6,
        img:require('../images/tvSamsungSeries5.jpg'),
        desc:"Smart TV Samsung Series 5 UN43T5300AGCZB LED Full HD 43",
        precio: 83.999,
        modelo: "UN43T5300AGCZB",
        categoria:"TV",
        voltaje:"220V - 240V",
        frecuencia:"50 Hz x 60 Hz",
        tipodepantalla:"LED",
        tamañodepantalla:"43",
        tipoderesolucion:"Full HD",
        conHDR:"Sí"
    },
    {
        id:7,
        img:require('../images/MarshallDSL.jpg'),
        desc:"Amplificador Marshall DSL DSL20CR Valvular para guitarra de 20W color negro/dorado 230V",
        precio: 428.533,
        categoria:"Amplificador",
        tipo:"Combo",
        tecnologia:"Valvular",
        alimentacion:"Corriente Eléctrica",
        instRecomendado:"Guitarra",
        cantidaddecanales:2,
        potenciadesalida:"20W",
        peso:"19Kg",
        color:"Negro"
    },
    {
        id:8,
        img:require('../images/VoxAc30HWH.jpg'),
        desc:"Amplificador VOX Hand-Wired Series AC30HWH Valvular guitarra de 30W",
        precio: 605.530,
        categoria:"Amplificador",
        tipo:"Cabezal",
        tecnologia:"Valvular",
        alimentacion:"Corriente Eléctrica",
        instRecomendado:"Guitarra",
        cantidaddecanales:2,
        potenciadesalida:"30W",
        peso:"20.3Kg",
        color:"Silver"
    },
    {
        id:9,
        img:require('../images/FenderHotRod.jpg'),
        desc:"Amplificador Fender Hot Rod Series Deluxe III Valvular para guitarra de 40W color negro/plata 220V",
        precio: 757.766,
        categoria:"Amplificador",
        tipo:"Combo",
        tecnologia:"Valvular",
        alimentacion:"Corriente Eléctrica",
        instRecomendado:"Guitarra",
        cantidaddecanales:2,
        potenciadesalida:"40W",
        peso:"23Kg",
        color:"Negro/Plata"
    },
    {
        id:10,
        img:require('../images/PlayStation5DigitalEdition.jpg'),
        desc:"Sony PlayStation 5 825GB Digital Edition  color blanco y negro",
        precio: 354.499,
        categoria:"Games",
        edicion:"Standard",
        color:"Blanco/Negro",
        capacidad:"825GB",
        tiposdememoria: "GDDR6",
        memoriaRam: "16GB",
        conWiFi: "Sí",
        conHDMI: "Sí",
        subModelo: "-" 
    },
    {
        id:11,
        img:require('../images/XBoxSerieX.jpg'),
        desc:"Microsoft Xbox Series X 1TB Standard  color negro",
        precio: 345.544,
        categoria:"Games",
        edicion:"Standard",
        color:"Negro",
        capacidad:"1TB",
        tiposdememoria: "GDDR6",
        memoriaRam: "16GB",
        conWiFi: "Sí",
        conHDMI: "-",
        subModelo: "X" 
    },
    {
        id:12,
        img:require('../images/XBoxSeriesS.jpg'),
        desc:"Microsoft Xbox Series S 512GB Standard  color blanco",
        precio: 239.077,
        categoria:"Games",
        edicion:"Standard",
        color:"Blanco",
        capacidad:"512GB",
        tiposdememoria: "GDDR6",
        memoriaRam: "10GB",
        conWiFi: "Sí",
        conHDMI: "-",
        subModelo: "S" 
    },
    {
        id:13,
        img:require('../images/Lusqtoff.jpg'),
        desc:"Maquina Cortar Pasto Lusqtoff",
        precio: 662.057,
        categoria:"Podadora",
        modelo:"Stratocaster",
        orientacion:"Diestro",
        color:"Olympic white",
        cuerpo:"Aliso",
        diapason:"Arce",
        acabado:"Uretano brillante",
        moddet:"-",
        origen:"Mexico",
        cantidad:1
    },
    {
        id:14,
        img:require('../images/Petri.jpg'),
        desc:"Maquina Cortar Pasto Petri",
        precio: 574.999,
        categoria:"Podadora",
        modelo:"Les Paul",
        orientacion:"Diestro",
        color:"Smokehouse burst",
        cuerpo:"Arce/Caoba",
        diapason:"Palo de rosa",
        acabado:"Brillante",
        moddet:"LPST00KHCH1",
        origen:"-",
        cantidad:2
    },
    {
        id:15,
        img:require('../images/Compac.jpg'),
        desc:"Maquina Cortar Pasto Compac",
        precio: 1.532475,
        categoria:"Podadora",
        modelo:"Les Paul",
        orientacion:"Diestro",
        color:"Cobalt burst",
        cuerpo:"Arce/Caoba",
        diapason:"Palo de rosa",
        acabado:"Brillante",
        moddet:"-",
        origen:"Mexico",
        cantidad:0
    },
    {
        id:16,
        img:require('../images/Reposera Alumel.jpg'),
        desc:"Reposera Cama Aluminio Brillante Alta Refozada 130 Kg Alumel",
        precio: 662.057,
        categoria:"Reposera",
        modelo:"Stratocaster",
        orientacion:"Diestro",
        color:"Olympic white",
        cuerpo:"Aliso",
        diapason:"Arce",
        acabado:"Uretano brillante",
        moddet:"-",
        origen:"Mexico",
        cantidad:1
    },
    {
        id:17,
        img:require('../images/Reposera Femmto.jpg'),
        desc:"Reposera Femmto X2 Silla Playera Plegable Reforzada Jardin",
        precio: 574.999,
        categoria:"Reposera",
        modelo:"Les Paul",
        orientacion:"Diestro",
        color:"Smokehouse burst",
        cuerpo:"Arce/Caoba",
        diapason:"Palo de rosa",
        acabado:"Brillante",
        moddet:"LPST00KHCH1",
        origen:"-",
        cantidad:2
    },
    {
        id:18,
        img:require('../images/Reposera Tumbona.jpg'),
        desc:"Reposera Playa Pileta Cama Reclinable Aluminio Tumbona Mor",
        precio: 1.532475,
        categoria:"Reposera",
        modelo:"Les Paul",
        orientacion:"Diestro",
        color:"Cobalt burst",
        cuerpo:"Arce/Caoba",
        diapason:"Palo de rosa",
        acabado:"Brillante",
        moddet:"-",
        origen:"Mexico",
        cantidad:0
    },
    {
        id:19,
        img:require('../images/Perfume Versace Red.jpg'),
        desc:"Versace Red Jeans EDT 75 ml para mujer",
        precio: 662.057,
        categoria:"Perfume",
        modelo:"Stratocaster",
        orientacion:"Diestro",
        color:"Olympic white",
        cuerpo:"Aliso",
        diapason:"Arce",
        acabado:"Uretano brillante",
        moddet:"-",
        origen:"Mexico",
        cantidad:1
    },
    {
        id:20,
        img:require('../images/Perfume Boos Pure.jpg'),
        desc:"Boos Pure Extreme EDP 100 ml para mujer",
        precio: 574.999,
        categoria:"Perfume",
        modelo:"Les Paul",
        orientacion:"Diestro",
        color:"Smokehouse burst",
        cuerpo:"Arce/Caoba",
        diapason:"Palo de rosa",
        acabado:"Brillante",
        moddet:"LPST00KHCH1",
        origen:"-",
        cantidad:2
    },
    {
        id:21,
        img:require('../images/Perfume Halloween.jpg'),
        desc:"Jesús del Pozo Halloween EDT 30 ml para mujer",
        precio: 1.532475,
        categoria:"Perfume",
        modelo:"Les Paul",
        orientacion:"Diestro",
        color:"Cobalt burst",
        cuerpo:"Arce/Caoba",
        diapason:"Palo de rosa",
        acabado:"Brillante",
        moddet:"-",
        origen:"Mexico",
        cantidad:0
    }
]

export default ListProdSimilares;