const ListProdVisitados = [
    {
        id:1,
        img:require('../images/TelecasterFender.jpg'),
        desc:"Guitarra eléctrica Fender American Vintage '52 Telecaster de fresno...",
        precio: 2.404465,
        categoria:"Guitarra Eléctrica",
        modelo:"Telecaster",
        orientacion:"Diestro",
        color:"Butterscotch blonde",
        cuerpo:"Fresno",
        diapason:"Arce",
        acabado:"Laca nitrocelulosa",
        moddet:"0110202850",
        origen:"USA",
        cantidad:0
    },
    {
        id:2,
        img:require('../images/FenderStrPlayer.jpg'),
        desc:"Guitarra eléctrica Fender Player Stratocaster de aliso black brillante con...",
        precio: 574.999,
        categoria:"Guitarra Eléctrica",
        modelo:"Stratocaster",
        orientacion:"Diestro",
        color:"Black",
        cuerpo:"Aliso",
        diapason:"Arce",
        acabado:"Brillante",
        moddet:"0144502506",
        origen:"-",
        cantidad:1
    },
    {
        id:3,
        img:require('../images/TelecasterOnas.jpg'),
        desc:"Guitarra eléctrica Onas TL telecaster de lenga blue wood laca con diapasón...",
        precio: 57.419,
        categoria:"Guitarra Eléctrica",
        modelo:"Telecaster",
        orientacion:"Diestro",
        color:"Blue wood",
        cuerpo:"Lenga",
        diapason:"Palo de rosa",
        acabado:"Laca",
        moddet:"-",
        origen:"-",
        cantidad:38
    },
    {
        id:4,
        img:require('../images/tvSamsungSeries6.jpg'),
        desc:"Smart TV Samsung Series 6 QN55Q60AAGCZB QLED 4K 55",
        precio: 179.999,
        modelo: "QN55Q60AAGCZB",
        categoria:"TV",
        voltaje:"220V - 240V",
        frecuencia:"50 Hz x 60 Hz",
        tipodepantalla:"QLED",
        tamañodepantalla:"55",
        tipoderesolucion:"4 K",
        conHDR:"Sí"
    },
    {
        id:5,
        img:require('../images/tvRCA.jpg'),
        desc:"Smart TV RCA AND55FXUHD LCD 4K 55 220V - 240V",
        precio: 123.999,
        modelo: "-",
        categoria:"TV",
        voltaje:"110V/240V",
        frecuencia:"50 Hz x 60 Hz",
        tipodepantalla:"LCD",
        tamañodepantalla:"55",
        tipoderesolucion:"4K",
        conHDR:"Sí"
    },
    {
        id:6,
        img:require('../images/tvTCLP7252.jpg'),
        desc:"Smart TV TCL P725-Series 55P725 DLED 4K 55 100V/240V",
        precio: 139.699,
        modelo: "-",
        categoria:"TV",
        voltaje:"220V - 240V",
        frecuencia:"50 Hz x 60 Hz",
        tipodepantalla:"LCD",
        tamañodepantalla:"55",
        tipoderesolucion:"4 K",
        conHDR:"Sí"
    }
]

export default ListProdVisitados;