const ListOfertasHome = [
    {
        id:5,
        img:require('../images/Daewoo.jpg'),
        img2:require('../images/img2LargeDaewoo.jpg'),
        img3:require('../images/img3LargeDaewoo.jpg'),
        imgsm1:require('../images/img1Daewoo.jpg'),
        imgsm2:require('../images/img2Daewoo.jpg'),
        imgsm3:require('../images/img3Daewoo.jpg'),
        categoria:"Guitarra Eléctrica",
        subcategoria:"Audio",
        subcategoria2:"Instrumentos Musicales",
        subcategoria3:"Instrumentos de Cuerdas",
        subcategoria4:"Guitarras",
        subcategoria5:"Eléctricas",
        titulo:"Guitarra eléctrica Fender American Vintage '56 Stratocaster de aliso/fresno black laca con diapasón de arce",
        titulosm:"Guitarra eléctrica Fender American Vintage '56 Stratocaster de aliso/fresno...",
        desc:"Maquina Cortar Pasto Desmalezadora 52cc 1.9Hp +",
        marca:"Fender",
        linea:"American Vintage",
        modelo:"'56 Stratocaster",
        formadelcuerpo: "Stratocaster",
        orientdelamano:"Diestro",
        color:"Black",
        tipomadcuerpo:"Aliso/Fresno",
        matdiapason:"Arce",
        acabadocuerpo:"Laca",
        detalles:["Fabricada en aliso/fresno con acabado de laca.","Con 6 cuerdas y 21 trastes.","El largo de escala es de 25.5 .","El puente es tremolo.","Incluye 3 micrófonos simples.","Controles de selector de micrófonos, tono y volumen.","Palanca incluida.","Sonidos fuertes y firmes con un estilo propio."],
        condicion:"Nuevo",
        cantvend:1,
        precio:26140,
        cuotas:"6x 4356.666 sin interés",
        vendedor:"CASALIBERTELLA",
        cantvendvendedor:1.461,
        tablacaracteristicas:[{titulo:"Marca",valor:"Fender"},{titulo:"Línea",valor:"American Vintage"},{titulo:"Modelo",valor:"'56 Stratocaster"},
                            {titulo:"Forma del cuerpo",valor:"Stratocaster"},{titulo:"Orientación de la mano",valor:"Diestro"},{titulo:"Color",valor:"Black"},
                            {titulo:"Tipo de madera del cuerpo",valor:"Aliso/Fresno"},{titulo:"Material del diapasón",valor:"Arce"},{titulo:"Acabado del cuerpo",valor:"Laca"}],
        caracteristicas:[{caracteristica:"Modelo detallado:",valor:"0111502806"},{caracteristica:"Cantidad de cuerdas:",valor:"6"},{caracteristica:"Con palanca:",valor:"Si"},
                        {caracteristica:"Es mini:",valor:"No"},{caracteristica:"Cantidad de trastes:",valor:"21"},{caracteristica:"Selector de micrófonos:",valor:"5 posiciones"},
                        {caracteristica:"Construcción del mástil:",valor:"Bolt-on"},{caracteristica:"Tipo de puente:",valor:"Tremolo"},{caracteristica:"Tipos de miscrófonos:",valor:"Simple"},
                        {caracteristica:"Tipo de micrófono medio:",valor:"New American Vintage '56 Strat"},{caracteristica:"Tipos de maderas del mástil:",valor:"Arce"},{caracteristica:"Largo de escala:",valor:"25.5"},
                        {caracteristica:"Con doble mástil:",valor:"No"},{caracteristica:"Es infantil:",valor:"No"},{caracteristica:"Cantidad de micrófonos:",valor:"3"},
                        {caracteristica:"Forma del mástil:",valor:"V"},{caracteristica:"Clasificación del tipo de puente:",valor:"Synch tremolo"},{caracteristica:"Tipos de control:",valor:"Selector de micrófonos, Tono, Volumeno"},
                        {caracteristica:"Tipo de micrófono mástil:",valor:"New American Vintage '56 Strat"},{caracteristica:"Tipo de micrófono puente:",valor:"New American Vintage '56 Strat"}],
        descripcion1:"Hablar de Fender es entender la música en todo el mundo y en muchos géneros. Es una de las marcas líderes en definir los sonidos que escuchamos. A su vez, satisface las necesidades de guitarristas al crear productos de calidad y respaldarlos con servicio y estabilidad...",
        descripcion2:"Una forma para cada estilo musical",
        descripcion3:"Esta Stratocaster es el máximo referente de las guitarras a lo largo de su historia. Cuenta con pastillas que incluyen selectores, tonos y volumen máster. Tiene un sonido cálido, cristalino, percusivo y con mucha textura. Su forma hace que sea el modelo que más se adapta al cuerpo humano, lo que otorga mayor versatilidad en su uso. Eric Clapton es el representante de este instrumento, por lo que es ideal para estilos como el rock y el blues.",
        prodsimilares : [["Precio","$ 1.473.260","$ 662.057","$ 574.999","$ 1.532475"],
                          ["Forma del cuerpo","Stratocaster","Stratocaster","Les Paul","Les Paul"],
                          ["Orientación de la mano","Diestro","Diestro","Diestro","Diestro"],
                          ["Color","Black","Olympic white","Smokehouse burst","Cobalt burst"],
                          ["Tipo de madera del cuerpo","Aliso/Fresno","Aliso","Arce/Caoba","Arce/Caoba"],
                          ["Material del diapasón","Arce","Arce","Palo de rosa","Palo de rosa"],
                          ["Acabado del cuerpo","Uretano Brillante","Brillante","Brillante","-"],
                          ["Modelo detallado","0111502806","-","LPST00KHCH1","-"],
                          ["Origen","-","Mexico","-","Mexico"]
                         ],
        prodvisitados : [["Precio","$ 1.473.260","$ 2.404465","$ 874.999","$ 57.419"],
                          ["Forma del cuerpo","Stratocaster","Telecaster","Stratocaster","Telecaster"],
                          ["Orientación de la mano","Diestro","Diestro","Diestro","Diestro"],
                          ["Color","Black","Butterscotch blonde","Black","Blue wood"],
                          ["Tipo de madera del cuerpo","Aliso/Fresno","Fresno","Aliso","Lenga"],
                          ["Material del diapasón","Arce","Arce","Arce","Palo de rosa"],
                          ["Acabado del cuerpo","Uretano Brillante","Laca nitrocelulosa","Brillante","Laca"],
                          ["Modelo detallado","0110202850","0144502506","LPST00KHCH1","-"],
                          ["Origen","-","USA","USA","Argentina"]
                         ]
    },
    {
        id:6,
        img:require('../images/ReposeraDakota.jpg'),
        img2:require('../images/img2LargeDakota.jpg'),
        img3:require('../images/img3LargeDakota.jpg'),
        imgsm1:require('../images/img1Dakota.jpg'),
        imgsm2:require('../images/img2Dakota.jpg'),
        imgsm3:require('../images/img3Dakota.jpg'),
        categoria:"Podadora",
        subcategoria:"Jardineria",
        subcategoria2:"Herramientas",
        subcategoria3:"Podadoras",
        subcategoria4:"Electricas",
        subcategoria5:"Cable",
        titulo:"Reposera Cama Reforzada 3 Posiciones Dakota Playa Pileta",
        titulosm:"Reposera Cama Reforzada 3 Posiciones Dakota Playa Pileta",
        desc:"Reposera Cama Reforzada 3 Posiciones Dakota Playa Pileta",
        marca:"Daewoo",
        linea:"Media",
        modelo:"52cc 1.9Hp +",
        color:"Naranja",
        detalles:[],
        condicion:"Nuevo",
        cantvend:1,
        precio:56140,
        cuotas:"6x 4356.666 sin interés",
        vendedor:"ELECTROHOGAR",
        cantvendvendedor:1.461,
        tablacaracteristicas:[{titulo:"Marca",valor:"Daewoo"},{titulo:"Modelo",valor:"Motoguadaña 2 Tiempo Jardinero Jardin Hogar"},{titulo:"Tipo",valor:"Desmalezadora"},
                            {titulo:"Motor",valor:"2 Tiempos/ 52 CC"},{titulo:"Potencia",valor:"1.9 HP (1,4kW)"},{titulo:" Velocidad Mínima",valor:"7500 rpm"},
                            {titulo:"Velocidad Máxima",valor:"9000 rpm"},{titulo:"Tanque de combustible",valor:"1,2 L"},{titulo:"Cabezal de corte (Cuchilla)",valor:"255mm"}],
        caracteristicas:[{caracteristica:"Modelo detallado:",valor:"52cc 1,9 Hp +"},{caracteristica:"Cantidad de cuchillas:",valor:"1"},{caracteristica:"Ancho de corte:",valor:"25 cm"},
                        {caracteristica:"Peso:",valor:"13 kg"},{caracteristica:"Cabezal:",valor:"Nylon"},{caracteristica:"Cuchilla:",valor:"3T"},
                        {caracteristica:"Protector de césped:",valor:"Si"},{caracteristica:"Tipo de arnés:",valor:"Arnés de hombro doble"},{caracteristica:"Kit de herramientas:",valor:"1"},
                        {caracteristica:"Diámetro Max. de corte (con tanza):",valor:"350mm"}],
        descripcion1:"Producto nuevo y sellado.",
        descripcion2:"Si esta Publicado es porque tenemos STOCK no necesitas consultarnos.",
        descripcion3:"Ofrecemos Retiro en Persona en nuestro local de Lunes a Viernes 10:30 a 17:00H / Sabado de 11:00 a las 14:00 H",
        prodsimilares : [["Precio","$ 56.140","$ 62.057","$ 74.999","$ 53.475"],
                          ["Marca","Daewoo","Lusqtoff","Petri","Compac"],
                          ["Modelo","ontaña 2 tiempo","Manual","Carro","Carro"],
                          ["Color","Naranja","Gris","Negra","Verde"],
                          ["Motor","2 tiempos","2 tiempos","2 tiempos","2 tiempos"],
                          ["Potencia","1.9HP","1.8HP","2.4HP","1.3HP"],
                          ["Velocidad Máxima","900 rpm","800 rpm","1200 rpm","800 rpm"],
                          ["Tanque de combustible","1,2 L","1 L","2,3 L","1 L"],
                          ["Cantidad de cuchillas","1","1","2","1"]
                         ],
        prodvisitados : [["Precio","$ 56.140","$ 80.000","$ 54.999","$ 63.475"],
                         ["Marca","Daewoo","Lusqtoff","Petri","Compac"],
                         ["Modelo","ontaña 2 tiempo","Manual","Carro","Manual"],
                         ["Color","Naranja","Gris","Negra","Naranja"],
                         ["Motor","2 tiempos","2 tiempos","2 tiempos","2 tiempos"],
                         ["Potencia","1.9HP","1.8HP","2.4HP","1.3HP"],
                         ["Velocidad Máxima","900 rpm","800 rpm","1200 rpm","800 rpm"],
                         ["Tanque de combustible","1,2 L","1 L","2,3 L","1 L"],
                         ["Cantidad de cuchillas","1","1","2","1"]
                         ]
    },
    {
        id:7,
        img:require('../images/Perfume.jpg'),
        desc:"Cacharel Amor Amor EDT 100ml para mujer",
        precio:11988,
        cuotas:"6x 1998 sin interés"
    },
    {
        id:8,
        img:require('../images/Somier.jpg'),
        desc:"Colchón Somier 11/2 Paza 190/90 Espuma Alta Densidad",
        precio:29723,
        cuotas:"6x 4953.833 sin interés"
    }
]

export default ListOfertasHome;