
const ListProductos = [
    {
        id:1,
        img:require('../images/img1LargeFenderStr.jpg'),
        img2:require('../images/img2LargeFenderStr.jpg'),
        img3:require('../images/img3LargeFenderStr.jpg'),
        imgsm1:require('../images/img1FenderStr.jpg'),
        imgsm2:require('../images/img2FenderStr.jpg'),
        imgsm3:require('../images/img3FenderStr.jpg'),
        categoria:"Guitarra Eléctrica",
        subcategoria:"Audio",
        subcategoria2:"Instrumentos Musicales",
        subcategoria3:"Instrumentos de Cuerdas",
        subcategoria4:"Guitarras",
        subcategoria5:"Eléctricas",
        titulo:"Guitarra eléctrica Fender American Vintage '56 Stratocaster de aliso/fresno black laca con diapasón de arce",
        titulosm:"Guitarra eléctrica Fender American Vintage '56 Stratocaster de aliso/fresno...",
        desc:"Guitarra Fender Am Standard Stratocaster Hss Limited Edition",
        marca:"Fender",
        linea:"American Vintage",
        modelo:"'56 Stratocaster",
        formadelcuerpo: "Stratocaster",
        orientdelamano:"Diestro",
        color:"Black",
        tipomadcuerpo:"Aliso/Fresno",
        matdiapason:"Arce",
        acabadocuerpo:"Laca",
        detalles:["Fabricada en aliso/fresno con acabado de laca.","Con 6 cuerdas y 21 trastes.","El largo de escala es de 25.5 .","El puente es tremolo.","Incluye 3 micrófonos simples.","Controles de selector de micrófonos, tono y volumen.","Palanca incluida.","Sonidos fuertes y firmes con un estilo propio."],
        condicion:"Nuevo",
        cantvend:1,
        precio:1403105,
        cuotas:"6x 108.333 sin interés",
        vendedor:"CASALIBERTELLA",
        cantvendvendedor:1.461,
        tablacaracteristicas:[{titulo:"Marca",valor:"Fender"},{titulo:"Línea",valor:"American Vintage"},{titulo:"Modelo",valor:"'56 Stratocaster"},
                            {titulo:"Forma del cuerpo",valor:"Stratocaster"},{titulo:"Orientación de la mano",valor:"Diestro"},{titulo:"Color",valor:"Black"},
                            {titulo:"Tipo de madera del cuerpo",valor:"Aliso/Fresno"},{titulo:"Material del diapasón",valor:"Arce"},{titulo:"Acabado del cuerpo",valor:"Laca"}],
        caracteristicas:[{caracteristica:"Modelo detallado:",valor:"0111502806"},{caracteristica:"Cantidad de cuerdas:",valor:"6"},{caracteristica:"Con palanca:",valor:"Si"},
                        {caracteristica:"Es mini:",valor:"No"},{caracteristica:"Cantidad de trastes:",valor:"21"},{caracteristica:"Selector de micrófonos:",valor:"5 posiciones"},
                        {caracteristica:"Construcción del mástil:",valor:"Bolt-on"},{caracteristica:"Tipo de puente:",valor:"Tremolo"},{caracteristica:"Tipos de miscrófonos:",valor:"Simple"},
                        {caracteristica:"Tipo de micrófono medio:",valor:"New American Vintage '56 Strat"},{caracteristica:"Tipos de maderas del mástil:",valor:"Arce"},{caracteristica:"Largo de escala:",valor:"25.5"},
                        {caracteristica:"Con doble mástil:",valor:"No"},{caracteristica:"Es infantil:",valor:"No"},{caracteristica:"Cantidad de micrófonos:",valor:"3"},
                        {caracteristica:"Forma del mástil:",valor:"V"},{caracteristica:"Clasificación del tipo de puente:",valor:"Synch tremolo"},{caracteristica:"Tipos de control:",valor:"Selector de micrófonos, Tono, Volumeno"},
                        {caracteristica:"Tipo de micrófono mástil:",valor:"New American Vintage '56 Strat"},{caracteristica:"Tipo de micrófono puente:",valor:"New American Vintage '56 Strat"}],
        descripcion1:"Hablar de Fender es entender la música en todo el mundo y en muchos géneros. Es una de las marcas líderes en definir los sonidos que escuchamos. A su vez, satisface las necesidades de guitarristas al crear productos de calidad y respaldarlos con servicio y estabilidad...",
        descripcion2:"Una forma para cada estilo musical",
        descripcion3:"Esta Stratocaster es el máximo referente de las guitarras a lo largo de su historia. Cuenta con pastillas que incluyen selectores, tonos y volumen máster. Tiene un sonido cálido, cristalino, percusivo y con mucha textura. Su forma hace que sea el modelo que más se adapta al cuerpo humano, lo que otorga mayor versatilidad en su uso. Eric Clapton es el representante de este instrumento, por lo que es ideal para estilos como el rock y el blues.",
        prodsimilares : [["Precio","$ 1.473.260","$ 662.057","$ 574.999","$ 1.532475"],
                          ["Forma del cuerpo","Stratocaster","Stratocaster","Les Paul","Les Paul"],
                          ["Orientación de la mano","Diestro","Diestro","Diestro","Diestro"],
                          ["Color","Black","Olympic white","Smokehouse burst","Cobalt burst"],
                          ["Tipo de madera del cuerpo","Aliso/Fresno","Aliso","Arce/Caoba","Arce/Caoba"],
                          ["Material del diapasón","Arce","Arce","Palo de rosa","Palo de rosa"],
                          ["Acabado del cuerpo","Uretano Brillante","Brillante","Brillante","-"],
                          ["Modelo detallado","0111502806","-","LPST00KHCH1","-"],
                          ["Origen","-","Mexico","-","Mexico"]
                         ],
        prodvisitados : [["Precio","$ 1.473.260","$ 2.404465","$ 874.999","$ 57.419"],
                          ["Forma del cuerpo","Stratocaster","Telecaster","Stratocaster","Telecaster"],
                          ["Orientación de la mano","Diestro","Diestro","Diestro","Diestro"],
                          ["Color","Black","Butterscotch blonde","Black","Blue wood"],
                          ["Tipo de madera del cuerpo","Aliso/Fresno","Fresno","Aliso","Lenga"],
                          ["Material del diapasón","Arce","Arce","Arce","Palo de rosa"],
                          ["Acabado del cuerpo","Uretano Brillante","Laca nitrocelulosa","Brillante","Laca"],
                          ["Modelo detallado","0110202850","0144502506","LPST00KHCH1","-"],
                          ["Origen","-","USA","USA","Argentina"]
                         ]
    },
    {
        id:2,
        img:require('../images/smartTVSamsung50.jpg'),
        img2:require('../images/tvSmart50img2.jpg'),
        img3:require('../images/tvSmart50img3.jpg'),
        imgsm1:require('../images/img1tvSmart50.jpg'),
        imgsm2:require('../images/img2tvSmart50.jpg'),
        imgsm3:require('../images/img3tvSmart50.jpg'),
        categoria:"TV",
        subcategoria:"Audio",
        subcategoria2:"Electrónica, Audio y Video",
        subcategoria3:"Tv",
        subcategoria4:"Smart",
        subcategoria5:"Televisores",
        desc:"Smart TV 50HD Samsung UNJ4290AGCZB",
        precio:2500000,
        detalles:["Su resolución es 4K.","Tecnología HDR, calidad de imagen mejorada.","Sonido: Dolby Digital Plus, Q-Symphony.","Tiene función Screen Share","Con Gallery, Web browser.","Sistema operativo Tizen.","Con 3 puertos HDMI y 1 USB.","Con sistema de cables ocultos.","Dimensiones: 123cm x 707cm x 5.99cm."],
        cuotas:"6x 41.666 sin interés",
        condicion:"Nuevo",
        cantvend:150,
        vendedor:"GARBARINO",
        cantvendvendedor:5.461,
        tablacaracteristicas:[{titulo:"Marca",valor:"Samsung"},{titulo:"Línea",valor:"Smart Tv"},{titulo:"Modelo",valor:"Uhd 4k Au7000"},
                            {titulo:"Tamaño de la pantalla",valor:"50 pulgadas"},{titulo:"Resolución",valor:"4K"},{titulo:"Es Smart",valor:"Sí"},
                            {titulo:"Cantidad de puertos HDMI",valor:"3"},{titulo:"Tipo de pantalla",valor:"Led"},{titulo:"Aplicaciones integradas",valor:"Web browser, Gallery, Netflix, Prime Video, Apple TV, YouTube."}],
        descripcion1:"Samsung es reconocida a nivel mundial como una empresa líder en la industria tecnológica. Todos sus productos son diseñados con una calidad superior y pensados para contribuir a un futuro mejor.",
        descripcion2:"Por eso, va a hacer que disfrutes de una experiencia visual incomparable. Con el Smart TV UN50AU7000G vas a acceder a las aplicaciones en las que se encuentran tus contenidos favoritos. Además, podés navegar por Internet, interactuar en redes sociales y divertirte con videojuegos.",
        descripcion3:"La cantidad de pixeles que ofrece es 4 veces mayor que la Full HD, ¿el resultado? Escenas mucho más realistas y con un nivel de detalle increíble. Ahora vas a conocer una aventura de inmersión que no va a dejar de sorprenderte.",
        prodsimilares : [["Precio","$ 152.999","$ 139.999","$ 120.999","$ 118.999"],
                          ["Modelo alfanumerico","UN55AU7000GCZB","UN50AU7000GCZB","55PUD7406","50PUD7406"],
                          ["Voltaje","220V - 240V","220V - 240V","110V/240V","110V/240V"],
                          ["Frecuencia","50 Hz x 60 Hz","50 Hz x 60 Hz","50 Hz x 60 Hz","50 Hz x 60 Hz"],
                          ["Tipo de pantalla","LED","LED","LED","LED"],
                          ["Tamaño de pantalla","55","50","55","50"],
                          ["Tipo de resolución","4K","4K","4K"],
                          ["Con HDR","SÍ","SÍ","SÍ","SÍ"]
                         ],
        prodvisitados : [["Precio","$ 182.999","$ 119.999","$ 108.999","$ 178.999"],
                         ["Modelo alfanumerico","UN99900GCZC","UN50AU7023GCFG","51115PUD7426","50YUPUD7400076"],
                         ["Voltaje","220V - 240V","220V - 240V","110V/240V","110V/240V"],
                         ["Frecuencia","50 Hz x 60 Hz","50 Hz x 60 Hz","50 Hz x 60 Hz","50 Hz x 60 Hz"],
                         ["Tipo de pantalla","LED","LED","LED","LED"],
                         ["Tamaño de pantalla","55","50","55","50"],
                         ["Tipo de resolución","4K","4K","4K"],
                         ["Con HDR","SÍ","SÍ","SÍ","SÍ"]
                        ]
    },
    {
        id:3,
        img:require('../images/img1MarshallStudio2525C.jpg'),
        img2:require('../images/img2MarshallStudio2525C.jpg'),
        img3:require('../images/img3MarshallStudio2525C.jpg'),
        imgsm1:require('../images/img1smallMarshalStudio2525c.jpg'),
        imgsm2:require('../images/img2smallMarshalStudio2525c.jpg'),
        imgsm3:require('../images/img3smallMarshalStudio2525c.jpg'),
        categoria:"Amplificador",
        subcategoria:"Audio",
        desc:"Marshall Studio 2525C amplificador valvular",
        precio:5500000,
        detalles:["Amplificador combo.","Tiene 2 canales.","Potencia de salida 20 W.","Tipo de conector de entrada: Jack 1/4.","Tipo de conector de salida: Jack 1/4.","Conseguí un sonido propio.","Pesa 19 kg.","Dimensiones: 47.5 cm x 49 cm x 28 cm."],
        cuotas:"6x 91.666 sin interés"
    },
    {
        id:4,
        img:require('../images/img1PlayStation5.jpg'),
        img2:require('../images/img2PlayStation5.jpg'),
        img3:require('../images/img3PlaStation5.jpg'),
        imgsm1:require('../images/img1smallPlayStation5.jpg'),
        imgsm2:require('../images/img2smallPlayStation5.jpg'),
        imgsm3:require('../images/img3smallPlayStation5.jpg'),
        categoria:"Games",
        subcategoria:"Audio",
        desc:"PlayStation 5",
        precio:309099,
        cuotas:"6x 51.516 sin interés"
    }
]

export default ListProductos;